### PR TITLE
Kanban board API enhancements

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
- added new search query to allow both AND and OR operator for labels
- Preview [link](https://near.org/megha19.near/widget/app?page=community&handle=devhub-platform&tab=github)

https://github.com/NEAR-DevHub/neardevhub-bos/assets/9760441/dd810bc3-569f-484e-889a-eea2d9d44ad7

### CODE REVIEW

**Comment by petersalomonsen** [comment]
Got this error message:

image

With this setup:

image

**Comment by Megha-Dev-19** [comment]
hey @petersalomonsen, thanks for pointing out this, I have added error handling, please check now.

**Comment by petersalomonsen** [comment]
Works now @Megha-Dev-19 . The code looks good to me. Should we add tests before merging the PR? Would need some extra days for that if so.

**Comment by Megha-Dev-19** [comment]
> Works now @Megha-Dev-19 . The code looks good to me. Should we add tests before merging the PR? Would need some extra days for that if so.

hey @petersalomonsen, yeah no worries, I m still waiting response from Ori about the changes, so you can add the tests and then we can merge it.

**Comment by Megha-Dev-19** [comment]
@petersalomonsen let's merge this PR too, wdyt?
We can add the tests later when you have time

**Comment by petersalomonsen** [comment]
> @petersalomonsen let's merge this PR too, wdyt? We can add the tests later when you have time

Yes we can merge it, I think the test I added for this still works. I see the addon test fails on this, but pulling the latest from main should fix that.

**Pull request merged**
