### PR TITLE
Make website occupy full screen width and Footer UI update

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
Preview [link](https://near.social/megha19.near/widget/app?page=feed)

### CODE REVIEW

**Comment by Megha-Dev-19** [comment]
Note: waiting for Ori's confirmation.

**Review by ailisp — APPROVED** [review]
Looks good to me

**Comment by ori-near** [comment]
Hi @Megha-Dev-19 and @ailisp – after discussing this further with Sasha, we agreed to not go full screen for now and instead just add the gray background #f4f4f4:

Before:
Screenshot 2024-02-20 at 6 34 26 AM

After:
photo_2024-02-20 06 33 18

Given that we have the option to go full screen now, we may consider optimizing for full screen in the coming quarter or so. But for now we can just do this quick fix.

**Comment by ailisp** [comment]
@Megha-Dev-19 Please fix ci as main branch passes

**Review by frol — APPROVED** [review]
Preview works as expected, the code looks fine

**Pull request merged**
