### PR TITLE
Use env for release and refactor to one file

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
Devhub [preview](https://near.social/megha19.near/widget/app?page=proposals)

### CODE REVIEW

**Comment by Megha-Dev-19** [comment]
@petersalomonsen thank you for your help with the most critical bracket change 🙏🏼

**Comment by petersalomonsen** [comment]
@race-of-sloths please include this PR

**Comment by race-of-sloths** [comment]
@Megha-Dev-19 Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
Great job! Usain Bolt jealous of your results!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/Megha-Dev-19?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/Megha-Dev-19?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/Megha-Dev-19)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/Megha-Dev-19)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Comment by petersalomonsen** [comment]
The output from the dry-run diff is quite a lot, are we sure that all of these changes are supposed to be there? For devhub I see removal of empty lines and comments. Is this because bos-workspace is processing the files first?

**Comment by Megha-Dev-19** [comment]
@petersalomonsen I think so, their formatting might be different then what we have, because I don't see any added/deleted widgets.
and for infra, there will be changes since earlier we used to import files and copy them, but now we use replacements for constants.

**Review by petersalomonsen — APPROVED** [review]
As long as we're ok with the diff, now when bos-workspace is building, then I think this looks good

**Comment by petersalomonsen** [comment]
@race-of-sloths score 3

**Comment by race-of-sloths** [comment]
### 🌟 Score recorded!

@petersalomonsen, thank you for scoring this pull request in the Race of Sloths!

**Comment by Megha-Dev-19** [comment]
@petersalomonsen linked the preview for devhub, it looks good.

**Comment by race-of-sloths** [comment]
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 3!
You have received 30 Sloth points for this contribution


We would appreciate your feedback or contribution idea that you can submit [here](https://github.com/NEAR-DevHub/race-of-sloths/issues/new/choose)

**Pull request merged**
