### PR TITLE
fix: copy url to proposal comment

### LINKED ISSUE #956: Copy Link button on proposal comment lacks the proposal id and points to the wrong portal
**Affected Portal:**
Select one: Infrastructure

**Description:**
When clicking the link button on a comment, you get a link to DevHub and not to infrastructure-committee

Image

For example clicking the link button on the comment here: https://infrastructure-committee.near.page/proposal/1?accountId=as2.near&blockHeight=124005661

It should give you that exact link, but instead it gives you this link:

https://devhub.near.page/proposal/?accountId=as2.near&blockHeight=124005661

And that link does not lead anywhere. It also lacks the proposal id.

**User Type:**
Specify: Regular User on web4 page

**Reproduction Steps**
1. Go to  https://infrastructure-committee.near.page/proposal/1?accountId=as2.near&blockHeight=124005661
2. Click on the Copy URL button as shown in the image above
3. The link you get is https://devhub.near.page/proposal/?accountId=as2.near&blockHeight=124005661 while it should have been https://infrastructure-committee.near.page/proposal/1?accountId=as2.near&blockHeight=124005661

**Expected behavior**
The link that should have been copied to your clipboard is: https://infrastructure-committee.near.page/proposal/1?accountId=as2.near&blockHeight=124005661

**Visual Reference**
If applicable, add screenshots or video recording to help explain your problem.

**Priority**
Select One: Medium (P2) – Major inconvenience

**Environment Details**
- Device: Desktop
- OS: Mac
- Browser Chrome

### PR DESCRIPTION
**Pull request by petersalomonsen**
The issue is fixed by pointing both events-committee and infrastructure-committee instances to the same `CommentsAndLogs.jsx` component devhub. The instance-specific versions of this component are deleted. The devhub version now also detects which instance that loaded it. Added an additional test for the like button, since this also now will be loaded via the devhub comments and logs component.

Another issue addressed is that the RFP comment test was still expecting the iframe for the preview, so it is updated to handle that we have switched back to the BOS built-in markdown viewer ( without iframe ).

Here's a reproduction of #956 in a playwright test

image

And here's the test video after fixing the issue

https://github.com/user-attachments/assets/fcfd3a3f-3934-45bf-9982-b922a42397bf

fixes #956

### CODE REVIEW

**Comment by petersalomonsen** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
### 🙁 This repository is not a part of the [Race of Sloths](https://race-of-sloths.com)
Please ask the maintainer to [contact us](https://github.com/NEAR-DevHub/race-of-sloths/issues/new/choose) to join the race!

<details><summary><strong>What is the Race of Sloths</strong></summary>
<p>

Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag us inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/petersalomonsen)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!

</p>
</details>

**Comment by petersalomonsen** [comment]
@race-of-sloths include

**Review by Megha-Dev-19 — APPROVED** [review]
Looks great, thanks for the cleanup and tests.

**Comment by Megha-Dev-19** [comment]
@race-of-sloths score 8

**Pull request merged**
