### PR TITLE
Fix blogs edit for community members

### LINKED ISSUE #597: Allow community admin to edit and delete previous blog posts
**Is your feature request related to a problem? Please describe.**
You cannot edit a blog after posting one.
You cannot delete a blog either

**Describe the solution you'd like**
If you are the author of a blog, you should be able to enter the blog post and click an icon to edit the blog. Also be able to delete them

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
Resolves #597
Preview [link](https://near.org/megha19.near/widget/app?page=blog&id=1997)

### CODE REVIEW

**Comment by Megha-Dev-19** [comment]
Note: I have not added "Edit" functionality through community blogs list page, I tried adding it, but there are a lot of child and parent components involved, so I ran into one or the other issue.
So you can only edit through that particular blog page
I hope for the time-being this is enough, we can refactor the code later on and add this feature here as well
image

**Comment by ailisp** [comment]
It's fine to only have edit button on specific blog page.
I'm getting this error when edit the preview blog:
```
{"index":0,"kind":{"ExecutionError":"Smart contract panicked: panicked at 'Failed to deserialize input from JSON.: Error(\"invalid type: null, expected a string\", line: 1, column: 32)', src/lib.rs:49:1"}}
```

possibly the error is the `null` in labels: 
image

**Comment by ailisp** [comment]
Another problem: when i edit this post: https://near.org/megha19.near/widget/app?page=blog&id=2943

it shows calling `add_post`, it should be `edit_post`:

image

**Comment by Megha-Dev-19** [comment]
Hey @ailisp, I tested it on one post and it worked well then, will look into this issues.

**Comment by Megha-Dev-19** [comment]
@ailisp fixed the issues that you mentioned, also made some updates so now user can edit any blog from configurations itself.

**Comment by ailisp** [comment]
Thank you, it looks great! I cannot update the above preview blog because I'm not the author or `devgovgigs.near`, but I can update my created posts, so I think it works.

There is a minor problem about layout: 

https://near.org/devhub.near/widget/app?page=blog&id=2953
https://near.org/megha19.near/widget/app?page=blog&id=2953

it should be not full page wide. Can you fix it?

**Comment by Megha-Dev-19** [comment]
Hey @ailisp, it’s full width because I have deployed the other PR changes #652, (together with this). If we merge only this PR, they won’t be there.

**Pull request merged**
