### PR TITLE
added post_type to notification

### PR DESCRIPTION
**Pull request by Tguntenaar**
_Resolves [#505](https://github.com/NEAR-DevHub/neardevhub-bos/issues/505)_

PR [#81](https://github.com/NEAR-DevHub/neardevhub-contract/pull/81) must be merged first, before proceeding with this PR.

### CODE REVIEW

**Comment by Megha-Dev-19** [comment]
hey @Tguntenaar 
We will have to update [mob.near](https://near.social/mob.near/widget/WidgetSource?src=mob.near/widget/Notification.Item.DevGov) and [near.org](https://github.com/near/near-discovery-components/blob/develop/src/NearOrg/Notifications/Notification.jsx#L173) code as well to send `post_type` in params

**Comment by Tguntenaar** [comment]
@Megha-Dev-19 I'm not sure what you mean, this can update independent of those widgets without them breaking right?

**Comment by Megha-Dev-19** [comment]
Hey @Tguntenaar 
your changes wouldn’t work if we don’t update those widgets, if you see closely we navigate to our widget from there. So if we don’t pass the post_type in params, we won’t receive it here.
I can create the PR if I m not able to explain it well.

**Comment by Tguntenaar** [comment]
Closing this issue to focus on the announcements, discussions, the new propposal workflow.

**Pull request closed without merging**
