### PR TITLE
Clean URL for community share button, proposal link tests for events committee

### LINKED ISSUE #889: Clean URL in community share button
as mentioned in #882, the share button in the screenshot below does not produce a "clean URL".

image

### PR DESCRIPTION
**Pull request by petersalomonsen**
https://github.com/user-attachments/assets/9d2c1139-ebc5-46c2-8d8a-64985232ee76

fixes #889

### CODE REVIEW

**Comment by petersalomonsen** [comment]
@race-of-sloths Please include this PR in the race

**Comment by race-of-sloths** [comment]
@petersalomonsen Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
Are you going to win race-of-sloths this month? If so, you should speed up! Run, Sloth, run!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/petersalomonsen?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/petersalomonsen?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/petersalomonsen)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/petersalomonsen)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Comment by petersalomonsen** [comment]
@Tguntenaar I still have the `proposal` folder included in the playwright config for `events`. Even `proposal.spec.js` does not pass, the two other test files in that folder does, so hoping that we can align the code and aim for also making all the proposal test pass at some point ( and will just keep it like that sine it will not affect the CI anyway, only local testing ).

**Review by Tguntenaar — APPROVED** [review]
@petersalomonsen yes I noticed that today as well. I've been working on merging the proposal tests into one file for all portals two weeks ago. I wasn't sure if it made it easier to maintain though so I kept it out of the events committee PR. They proposals differ quiet a lot from eachother labels / names / id / authors. Which all can be defined per playwright project. 

I can make a PR for it, but again not sure if it becomes easier or harder to maintain at that point.

**Comment by petersalomonsen** [comment]
> @petersalomonsen yes I noticed that today as well. I've been working on merging the proposal tests into one file for all portals two weeks ago. I wasn't sure if it made it easier to maintain though so I kept it out of the events committee PR. They proposals differ quiet a lot from eachother labels / names / id / authors. Which all can be defined per playwright project.
> 
> I can make a PR for it, but again not sure if it becomes easier or harder to maintain at that point.

I think it makes sense to keep what's specific to a portal in a dedicated file for that portal. We will have to see if we can make the proposals more equal across portals and more configurable for the differences, but it depends. Configurability comes with a maintenance cost too. Let's start by extracting those features that are indeed common and have them tested across all instances, such as the proposal comments and links that are now separate files.

**Comment by Megha-Dev-19** [comment]
@race-of-sloths score 3

**Comment by race-of-sloths** [comment]
### 🌟 Score recorded!

@Megha-Dev-19, thank you for scoring this pull request in the Race of Sloths!

**Comment by race-of-sloths** [comment]
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 3!
You have received 30 Sloth points for this contribution


We would appreciate your feedback or contribution idea that you can submit [here](https://github.com/NEAR-DevHub/race-of-sloths/issues/new/choose)

**Pull request merged**
