### PR TITLE
Feature/883 extra replacements variables events committee

### PR DESCRIPTION
**Pull request by Tguntenaar**
_Resolves #883_

### CODE REVIEW

**Comment by Tguntenaar** [comment]
@race-of-sloths please include my PR in the race

**Comment by race-of-sloths** [comment]
### ❓Unknown command 
Please check the command and try again

**Review by Megha-Dev-19 — APPROVED** [review]

**Comment by race-of-sloths** [comment]
### ❓Unknown command 
Please check the command and try again

**Comment by Megha-Dev-19** [comment]
@race-of-sloths  include

**Comment by akorchyn** [comment]
Hey, sorry. It seems like some bug happened.
The PR is included already. That's why it can't resolve it 

https://race-of-sloths.com/profile/Tguntenaar

Feel free to score it now

**Comment by Megha-Dev-19** [comment]
@race-of-sloths score 1

**Comment by race-of-sloths** [comment]
### 🌟 Score recorded!

@Megha-Dev-19, thank you for scoring this pull request in the Race of Sloths!

**Comment by Tguntenaar** [comment]
> Hey, sorry. It seems like some bug happened. The PR is included already. That's why it can't resolve it

@akorchyn Hmmm, I think that is my fault, it might have happend because I added @ race of sloths in the issue at first, removed it and referenced it in the PR.

**Comment by race-of-sloths** [comment]
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 1!
You have received 25 (10 base + 15 weekly bonus) Sloth points for this contribution


Another weekly streak completed, well done @Tguntenaar! To keep your weekly streak and get another bonus make pull request next week! Looking forward to see you in race-of-sloths

**Pull request merged**
