### PR TITLE
Removing default tabs

### PR DESCRIPTION
**Pull request by Tguntenaar**
_Resolves #709_
_Resolves #587_

This PR removes the default tabs. First these things need to happen:

- [x] A moderator in the devhub.near contract calls `create_addon` 4 times to add the addons. (I will add the arguments below)
- [x] The communities we use in tests need to either enable these addons or we need to mock that the addons are enabled. 
- [x] The announcement discussions activity and teams tab tests need to be re-run and succeed 
- [x] Create a script to enable the addons on all communities
- [x] Execute the script @frol and merge
- [ ] Merge

[Testnet preview](https://test.near.org/thomasguntenaar.testnet/widget/app?page=community&handle=test)

### CODE REVIEW

**Comment by Tguntenaar** [comment]
# Announcement arguments
```json
{
    "configurator_widget": "",
    "description": "Create an announcements page for your community",
    "icon": "bi bi-megaphone",
    "id": "announcements",
    "title": "Announcements",
    "view_widget": "devhub.near/widget/devhub.entity.community.Announcements"
}
```
### near-cli-rs call
```zsh
near contract call-function as-transaction devhub.near create_addon json-args '{"addon":{"configurator_widget": "","description": "Create an announcements page for your community","icon": "bi bi-megaphone","id": "announcements","title": "Announcements","view_widget": "devhub.near/widget/devhub.entity.community.Announcements"
}}' prepaid-gas '100.000 TeraGas' attached-deposit '0 NEAR' sign-as {{SIGNER}} network-config mainnet sign-with-keychain send
```

# Discussions arguments
```json
{
    "configurator_widget": "",
    "description": "Create an discussions page for your community",
    "icon": "bi bi-chat-dots",
    "id": "discussions",
    "title": "Discussions",
    "view_widget": "devhub.near/widget/devhub.entity.community.Discussions"
}
```
### near-cli-rs call
```zsh
near contract call-function as-transaction devhub.near create_addon json-args '{"addon":{"configurator_widget": "","description": "Create an discussions page for your community","icon": "bi bi-chat-dots","id": "discussions","title": "Discussions","view_widget": "devhub.near/widget/devhub.entity.community.Discussions"}}' prepaid-gas '100.000 TeraGas' attached-deposit '0 NEAR' sign-as {{SIGNER}} network-config mainnet sign-with-keychain send
```
# Activity arguments
```json
{
    "configurator_widget": "",
    "description": "Create an activity page for your community",
    "icon": "bi bi-activity",
    "id": "activity",
    "title": "Activity",
    "view_widget": "devhub.near/widget/devhub.entity.community.Activity"
}
```
### near-cli-rs call
```zsh
near contract call-function as-transaction devhub.near create_addon json-args '{"addon":{"configurator_widget": "","description": "Create an activity page for your community","icon": "bi bi-activity","id": "activity","title":"Activity","view_widget":"devhub.near/widget/devhub.entity.community.Activity"}}' prepaid-gas '100.000 TeraGas' attached-deposit '0 NEAR' sign-as {{SIGNER}} network-config mainnet sign-with-keychain send
```
# Teams arguments
```json
{
    "configurator_widget": "",
    "description": "Create an teams page for your community",
    "icon": "bi bi-people",
    "id": "teams",
    "title": "Teams",
    "view_widget": "devhub.near/widget/devhub.entity.community.Teams"
}
```
### near-cli-rs call
```zsh
near contract call-function as-transaction devhub.near create_addon json-args '{"addon":{"configurator_widget": "","description": "Create an teams page for your community","icon": "bi bi-people","id": "teams","title": "Teams","view_widget": "devhub.near/widget/devhub.entity.community.Teams"}}' prepaid-gas '100.000 TeraGas' attached-deposit '0 NEAR' sign-as {{SIGNER}} network-config mainnet sign-with-keychain send
```

**Comment by frol** [comment]
@Tguntenaar I have added the addons and tested manually that they work

**Comment by Tguntenaar** [comment]
@petersalomonsen I added Announcements Discussions and Activity as addons to webassembly music to rerun the tests. Preferebly we make the test independent of the configuration of the community webassemblymusic. Is there a way to mock the tabs as if they are active? Or should we just create another community specifically for testing purposes.

**Comment by petersalomonsen** [comment]
> @petersalomonsen I added Announcements Discussions and Activity as addons to webassembly music to rerun the tests. Preferebly we make the test independent of the configuration of the community webassemblymusic. Is there a way to mock the tabs as if they are active? Or should we just create another community specifically for testing purposes.

Sorry for not seeing this message before now, but I believe we discussed this already on TG, and your implementation of mocking the RPC looks great!

**Review by Tguntenaar — COMMENTED** [review]
Ready for review

**Pull request merged**
